- name: Configure FreeNAS appliances
  hosts: freenas
  connection: local
  tasks:
    - include: account/users.yml
    - include: network/global.yml
    - include: system/email.yml
    - include: services/services.yml
    - include: services/smart.yml
    - include: storage/scrub.yml
    - include: tasks/smart.yml
