---
freenas:
  hosts:
    - ops-nas-1.example.com
    - ops-nas-2.example.com

  vars:
    ansible_ssh_user: root
    api:
      email: /api/v1.0/system/email/
      services: /api/v1.0/services/services/
      smart_service_settings: /api/v1.0/services/smart/
      users: /api/v1.0/account/users/
    email:
      fromemail: "nas@example.com"
      outgoingserver: ops-smtp-1.example.com
      pass: ""
      port: 25
      security: plain
      smtp: false
      user: ""
    services:
      smartd: true
      ssh: true
      cifs: true
    smart_service:
      interval: 30
      powermode: never
      difference: 5
      informational: 40
      critical: 45
      email: chris@example.com
    users:
      root:
        id: 1
        email: chris@example.com
      