---
freenas:
  hosts:
    ops-nas-1.farm.oakops.io:
      network:
        nameserver1: 172.21.14.2
        nameserver2: 172.21.14.4
        nameserver3: 172.21.7.5
      storage:
        scrubs:
          - daymonth: "*"
            dayweek: "7"
            description: ""
            enabled: true
            hour: "02"
            minute: "00"
            month: "*"
            threshold: 6
            volume: "POOL_A"
          - daymonth: "*"
            dayweek: "7"
            description: ""
            enabled: true
            hour: "00"
            minute: "00"
            month: "*"
            threshold: 35
            volume: "nas1-vol1"

  vars:
    ansible_ssh_user: root
    api:
      email: /api/v1.0/system/email/
      services: /api/v1.0/services/services/
      smart_service_settings: /api/v1.0/services/smart/
      users: /api/v1.0/account/users/
      network_global: /api/v1.0/network/globalconfiguration/
      storage_scrub: /api/v1.0/storage/scrub/
      storage_volume: /api/v1.0/storage/volume/
    email:
      fromemail: "alerts@oakops.io"
      outgoingserver: ops-smtp-1.farm.oakops.io
      pass: ""
      port: 25
      security: plain
      smtp_auth: false
      user: ""
    services:
      smartd: true
      ssh: true
      cifs: true
    smart_service:
      interval: 30
      powermode: never
      difference: 5
      informational: 40
      critical: 45
      email: alerts@oakops.io
    users:
      root:
        id: 1
        email: alerts@oakops.io
      